# Purpose: Descriptions of example data
# Updated: 180408

#' Simulated Data
#' 
#' Example data for 1000 subjects. Outcomes were generated by adding standard
#' normal residuals to the vector of means. The outcome means depend on a model
#' matrix containing an intercept and three N(0,1) covariates.
#' 
#' @format A list of vectors and matrices. 
#' \describe{ 
#'    \item{y}{Numeric outcome vector.}
#'    \item{Z}{Numeric model matrix.}
#'    \item{Beta}{Regression coefficients used to generate the outcome.}
#' }
"D"

