# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Matrix vector product
#'
#' Calculates \eqn{Ab};
#'
#' @param A Numeric matrix.
#' @param b Numeric vector.
#' @export
fastMvp <- function(A, b) {
    .Call('_NST_fastMvp', PACKAGE = 'NST', A, b)
}

#' Matrix matrix product
#'
#' Calculates \eqn{AB};
#'
#' @param A Numeric matrix.
#' @param B Numeric matrix.
#' @export
fastMMp <- function(A, B) {
    .Call('_NST_fastMMp', PACKAGE = 'NST', A, B)
}

#' Matrix Transpose
#'
#' Constructs \eqn{A'} from \eqn{A}.
#'
#' @param A Numeric matrix.
#' @export
fastT <- function(A) {
    .Call('_NST_fastT', PACKAGE = 'NST', A)
}

#' Matrix Inner Product
#'
#' Calculates \eqn{A'B}.
#'
#' @param A Numeric matrix.
#' @param B Numeric matrix.
#' @export
fastIP <- function(A, B) {
    .Call('_NST_fastIP', PACKAGE = 'NST', A, B)
}

#' Matrix Inverse
#'
#' @param A Numeric matrix.
#' @export
fastInv <- function(A) {
    .Call('_NST_fastInv', PACKAGE = 'NST', A)
}

#' Matrix Determinant
#'
#' Calculates \eqn{\det(A)}.
#'
#' @param A Numeric matrix.
#' @export
fastDet <- function(A) {
    .Call('_NST_fastDet', PACKAGE = 'NST', A)
}

#' Quadratic Form
#' 
#' Calculates \eqn{x'Ax}.
#' 
#' @param x Numeric vector.
#' @param A Numeric matrix.
#' @export
vecQF <- function(x, A) {
    .Call('_NST_vecQF', PACKAGE = 'NST', x, A)
}

#' Matrix Quadratic Form
#' 
#' Calculates \eqn{x'Ax}.
#' 
#' @param X Numeric matrix.
#' @param A Numeric matrix.
#' @export
matQF <- function(X, A) {
    .Call('_NST_matQF', PACKAGE = 'NST', X, A)
}

#' Incomplete projection
#' 
#' Form the incomplete projection \eqn{(A'A)^{-1}A};
#' 
#' @param A Numeric matrix
#' @export
incP <- function(A) {
    .Call('_NST_incP', PACKAGE = 'NST', A)
}

#' Schur complement
#'
#' Calculates the efficient information \eqn{I_{11}-I_{12}I_{22}^{-1}I_{21}};
#'
#' @param I11 Information of target parameter
#' @param I22 Information of nuisance parameter
#' @param I12 Cross information between target and nuisance parameters
#' @export
#'
SchurC <- function(I11, I22, I12) {
    .Call('_NST_SchurC', PACKAGE = 'NST', I11, I22, I12)
}

#' Normal Score Statistic
#' 
#' @param y Outcome.
#' @param X1 Model matrix whose coefficient is fixed.
#' @param b Values at which the coefficients of X1 are fixed.
#' @param X2 Model matrix whose coefficient is estimated.
#' @param estT Logical indicating tau should be estimated. If false, provide the
#'   known value.
#' @param t Variance component, if known.
#' @param useK Logical indicating that a known covariance structure is supplied.
#' @param K Covariance structure, if known.
normScore <- function(y, X1, b, X2, estT, t, useK, K) {
    .Call('_NST_normScore', PACKAGE = 'NST', y, X1, b, X2, estT, t, useK, K)
}

#' Weighted Normal Score Statistic
#' 
#' @param y Outcome.
#' @param X1 Model matrix whose coefficient is fixed.
#' @param b Values at which the coefficients of X1 are fixed.
#' @param X2 Model matrix whose coefficient is estimated.
#' @param estT Logical indicating tau should be estimated. If false, provide the
#'   known value.
#' @param t Variance component, if known.
#' @param useK Logical indicating that a known covariance structure is supplied.
#' @param K Covariance structure, if known.
#' @param W Weight matrix
wNormScore <- function(y, X1, b, X2, estT, t, useK, K, W) {
    .Call('_NST_wNormScore', PACKAGE = 'NST', y, X1, b, X2, estT, t, useK, K, W)
}

#' Normal Model
#' 
#' @param y Outcome.
#' @param Z Model matrix.
#' @param estT Logical indicating tau should be estimated. If false, provide the
#'   known value.
#' @param t Variance component, if known.
fitNorm <- function(y, Z, estT, t) {
    .Call('_NST_fitNorm', PACKAGE = 'NST', y, Z, estT, t)
}

