# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Univariate OLS model.
#' 
#' Fits the standard OLS model.
#' 
#' @param y Outcome.
#' @param Z Model matrix.
#' @export 
#' 
#' @return A list containing the following:
#' \item{Beta}{Regression coefficient.}
#' \item{Tau}{Outcome variance.}
#' \item{Ibb}{Information matrix for beta.}
#' \item{Resid}{Outcome residuals.}
#' 
fitNorm <- function(y, Z) {
    .Call('_NST_fitNorm', PACKAGE = 'NST', y, Z)
}

#' Matrix Trace
#'
#' Calculates the trace of a matrix \eqn{A}.
#'
#' @param A Numeric matrix.
#' @export
#' @return A scalar. 
tr <- function(A) {
    .Call('_NST_tr', PACKAGE = 'NST', A)
}

#' Matrix Matrix Product
#'
#' Calculates the product \eqn{AB}. 
#'
#' @param A Numeric matrix.
#' @param B Numeric matrix.
#' @export
#' @return A numeric matrix. 
fastMMp <- function(A, B) {
    .Call('_NST_fastMMp', PACKAGE = 'NST', A, B)
}

#' Matrix Transpose
#'
#' Constructs \eqn{A'} from \eqn{A}.
#'
#' @param A Numeric matrix.
#' @export
fastT <- function(A) {
    .Call('_NST_fastT', PACKAGE = 'NST', A)
}

#' Matrix Inner Product
#'
#' Calculates the product \eqn{A'B}.
#'
#' @param A Numeric matrix.
#' @param B Numeric matrix.
#' @export
#' @return A numeric matrix. 
fastIP <- function(A, B) {
    .Call('_NST_fastIP', PACKAGE = 'NST', A, B)
}

#' Matrix Inverse
#' 
#' Calcualtes \eqn{A^{-1}}.
#'
#' @param A Numeric matrix.
#' @export
#' @return A numeric matrix. 
fastInv <- function(A) {
    .Call('_NST_fastInv', PACKAGE = 'NST', A)
}

#' Matrix Determinant
#'
#' Calculates the determinant of \eqn{A}.
#'
#' @param A Numeric matrix.
#' @export
#' @return A scalar. 
fastDet <- function(A) {
    .Call('_NST_fastDet', PACKAGE = 'NST', A)
}

#' Quadratic Form
#' 
#' Calculates the quadratic form \eqn{x'Ax}.
#' 
#' @param X Numeric matrix.
#' @param A Numeric matrix.
#' @export
fastQF <- function(X, A) {
    .Call('_NST_fastQF', PACKAGE = 'NST', X, A)
}

#' Schur complement
#'
#' Calculates the efficient information \eqn{I_{11}-I_{12}I_{22}^{-1}I_{21}}. 
#'
#' @param I11 Information of target parameter
#' @param I22 Information of nuisance parameter
#' @param I12 Cross information between target and nuisance parameters
#' @export
#' @return A numeric matrix. 
#'
SchurC <- function(I11, I22, I12) {
    .Call('_NST_SchurC', PACKAGE = 'NST', I11, I22, I12)
}

