# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generate Exchangable Correlation Structure
#' 
#' @param n Dimension
#' @param r Correlation
#' @export
exchCorr <- function(n, r) {
    .Call('_ScoreTest_exchCorr', PACKAGE = 'ScoreTest', n, r)
}

#' Estimate Alpha under H0
#' 
#' Estimates coefficient on nuisance parameter under the \eqn{H_{0}:\beta=0}.
#' @param X Design matrix for alpha, numeric.
#' @param R Correlation structure, numeric.
#' @param y Response, numeric.
#' 
Alpha0 <- function(X, R, y) {
    .Call('_ScoreTest_Alpha0', PACKAGE = 'ScoreTest', X, R, y)
}

#' Estimates Tau under H1
#' 
#' Estimate the variance component \eqn{\tau} under the full model.
#' 
#' @param D Overall design matrix, numeric.
#' @param R Correlation structure, numeric.
#' @param y Response, numeric.
#' 
Tau1 <- function(D, R, y) {
    .Call('_ScoreTest_Tau1', PACKAGE = 'ScoreTest', D, R, y)
}

#' Estimate Information Matrix
#' 
#' Estimate information matrix for \eqn{(\beta,\alpha)}.
#' 
#' @param X Design matrix for alpha, numeric.
#' @param G Design matrix for beta, numeric. 
#' @param R Correlation structure, numeric.
#' @param tau Variance component, numeric.
#' 
Info <- function(X, G, R, tau) {
    .Call('_ScoreTest_Info', PACKAGE = 'ScoreTest', X, G, R, tau)
}

#' Schur Complement
#' 
#' Calcualtes the matrix \deqn{I_{gg}-I_{gh}I_{hh}^{-1}I_{gh}'}
#' @param Igg First information matrix.
#' @param Ihh Second information matrix.
#' @param Igh Cross information matrix.
#' @param inv Return the inverse of 
#' 
#' @export  
SchurC <- function(Igg, Ihh, Igh, inv) {
    .Call('_ScoreTest_SchurC', PACKAGE = 'ScoreTest', Igg, Ihh, Igh, inv)
}

#' Calculate Score under H0
#' 
#' Calculate the score vector for \eqn{\beta} under \eqn{H_{0}:\beta=0}.
#' 
#' @param e0 Residuals under H0, numeric.
#' @param G Design matrix for beta, numeric. 
#' @param R Correlation structure, numeric.
#' @param tau Variance component, numeric.
#' 
ScoreB <- function(e0, G, R, tau) {
    .Call('_ScoreTest_ScoreB', PACKAGE = 'ScoreTest', e0, G, R, tau)
}

#' Quadratic Form
#' 
#' @param K Numeric matrix.
#' @param s Numeric vector
#' @export
qForm <- function(K, s) {
    .Call('_ScoreTest_qForm', PACKAGE = 'ScoreTest', K, s)
}

